# Generated by Django 5.1.7 on 2025-08-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='audio_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
