# Generated by Django 5.1.7 on 2025-08-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_answer_audio_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
